const KEY='scorezero_rooms_v1';
const $=s=>document.querySelector(s);
const uid=()=>Math.random().toString(36).slice(2,9);
const code=()=>Math.random().toString(36).slice(2,8).toUpperCase();
let state={screen:'home',room:null,modal:null,toast:''};
function loadRooms(){return JSON.parse(localStorage.getItem(KEY)||'{}')}
function saveRooms(rooms){localStorage.setItem(KEY,JSON.stringify(rooms))}
function saveRoom(room){const rooms=loadRooms();rooms[room.code]=room;saveRooms(rooms);state.room=room;}
function fmt(n){return (n>0?'+':'')+n}
function total(room){return room.players.reduce((a,p)=>a+Number(p.score||0),0)}
function recalc(room){room.players.forEach(p=>p.score=Number(p.startScore||0));room.records.forEach(r=>r.items.forEach(it=>{let p=room.players.find(x=>x.id===it.playerId);if(p)p.score+=Number(it.points||0)}));}
function toast(t){state.toast=t;render();setTimeout(()=>{state.toast='';render()},1800)}
function render(){document.getElementById('app').innerHTML = `<div class="wrap">${views[state.screen]()}${state.toast?`<div class="toast">${state.toast}</div>`:''}</div>${state.modal?modals[state.modal]():''}`; bind();}
const views={
 home(){return `<div class="topbar"><div><div class="brand">ScoreZero</div><div class="sub">多人同步記分器｜PWA原型</div></div></div><div class="card"><h2>開始記分</h2><p class="muted">適合捉遊、桌遊、麻將、撲克牌。總和為 0 會顯示綠色，不為 0 顯示紅色。</p><div class="grid"><button data-act="createSetup">建立房間</button><button class="secondary" data-act="joinSetup">加入房間</button></div><button class="secondary" style="width:100%;margin-top:10px" data-act="localDemo">快速單機示範</button></div><div class="card"><b>目前版本說明</b><p class="muted">這是可直接打開使用的網頁原型，資料存在本機瀏覽器。要做到不同手機真正即時同步，下一版需接 Firebase。</p></div>`},
 room(){const r=state.room; const sum=total(r); return `<div class="topbar"><div><div class="brand">${r.name}</div><div class="sub">房號 ${r.code}</div></div><button class="secondary small" data-act="home">首頁</button></div><div class="scoreSum ${sum===0?'sumGood':'sumBad'}">總和：${fmt(sum)}</div><div class="card"><div class="row"><button data-act="openAdd">新增紀錄</button><button class="secondary" data-act="openPlayers">玩家</button></div><div class="row" style="margin-top:10px"><button class="secondary" data-act="openHistory">歷史紀錄</button><button class="danger" data-act="undo">撤銷上一筆</button></div></div><div class="card"><div class="row" style="justify-content:space-between"><h3 style="margin:0">目前分數</h3><span class="pill">${r.players.length} 位玩家</span></div>${r.players.sort((a,b)=>b.score-a.score).map(p=>`<div class="player"><div class="pname">${p.name}<div class="sub">起始 ${p.startScore}</div></div><div class="pscore ${p.score>0?'pos':p.score<0?'neg':'zero'}">${fmt(p.score)}</div></div>`).join('')}</div>`}
};
const modals={
 create(){return `<div class="modal"><div class="sheet"><h2>建立房間</h2><div class="field"><label>房間名稱</label><input id="roomName" value="今晚記分"></div><div class="field"><label>玩家暱稱，用逗號分隔</label><input id="names" value="阿明,小華,阿偉"></div><div class="field"><label>起始點數</label><input id="start" type="number" value="0"></div><label class="row" style="justify-content:flex-start"><input id="zero" type="checkbox" checked> <span>開啟總和歸零檢查</span></label><div class="grid" style="margin-top:14px"><button data-act="createRoom">建立</button><button class="secondary" data-act="closeModal">取消</button></div></div></div>`},
 join(){return `<div class="modal"><div class="sheet"><h2>加入房間</h2><div class="field"><label>房號</label><input id="joinCode" placeholder="例如 A7K29Q"></div><div class="field"><label>你的暱稱</label><input id="joinName" placeholder="輸入暱稱"></div><div class="grid"><button data-act="joinRoom">加入</button><button class="secondary" data-act="closeModal">取消</button></div><p class="muted">目前原型只能加入同一台手機建立過的房間；Firebase 版才支援不同手機同步。</p></div></div>`},
 add(){const r=state.room;return `<div class="modal"><div class="sheet"><h2>新增紀錄</h2><p class="muted">一次至少輸入一個扣分與一個加分，送出後會留下歷史紀錄。</p><div id="entryList">${r.players.map(p=>`<div class="row field"><div><label>${p.name}</label><input data-player="${p.id}" type="number" value="0"></div></div>`).join('')}</div><div class="quick">${[10,20,30,50,100,-10,-20,-30,-50,-100].map(n=>`<button class="secondary" data-quick="${n}">${fmt(n)}</button>`).join('')}</div><div class="field"><label>備註</label><input id="note" placeholder="可不填"></div><div class="grid"><button data-act="submitRecord">送出</button><button class="secondary" data-act="closeModal">取消</button></div></div></div>`},
 players(){const r=state.room;return `<div class="modal"><div class="sheet"><h2>玩家管理</h2>${r.players.map(p=>`<div class="row field"><input data-name="${p.id}" value="${p.name}"><input data-start="${p.id}" type="number" value="${p.startScore}"></div>`).join('')}<div class="divider"></div><div class="row"><input id="newPlayer" placeholder="新增玩家暱稱"><input id="newStart" type="number" value="0"></div><div class="grid" style="margin-top:12px"><button data-act="savePlayers">儲存</button><button class="secondary" data-act="closeModal">關閉</button></div></div></div>`},
 history(){const r=state.room;return `<div class="modal"><div class="sheet"><h2>歷史紀錄</h2>${r.records.length? [...r.records].reverse().map((rec,i)=>`<div class="historyItem"><div class="histTop"><span>第 ${r.records.length-i} 筆｜${new Date(rec.createdAt).toLocaleTimeString()}</span><button class="danger small" data-delrec="${rec.id}">刪除</button></div><div class="changes">${rec.items.map(it=>`${r.players.find(p=>p.id===it.playerId)?.name||'玩家'} ${fmt(it.points)}`).join('　')}</div>${rec.note?`<div class="sub">${rec.note}</div>`:''}</div>`).join(''):'<p class="muted">尚無紀錄</p>'}<button class="secondary" style="width:100%" data-act="closeModal">關閉</button></div></div>`}
};
function bind(){document.querySelectorAll('[data-act]').forEach(b=>b.onclick=()=>act(b.dataset.act));document.querySelectorAll('[data-quick]').forEach(b=>b.onclick=()=>{let focused=document.activeElement;if(focused&&focused.dataset.player){focused.value=Number(focused.value||0)+Number(b.dataset.quick)}});document.querySelectorAll('[data-delrec]').forEach(b=>b.onclick=()=>{let r=state.room;r.records=r.records.filter(x=>x.id!==b.dataset.delrec);recalc(r);saveRoom(r);state.modal='history';render();});}
function act(a){let r=state.room;if(a==='home'){state.screen='home';state.modal=null;render()} if(a==='createSetup'){state.modal='create';render()} if(a==='joinSetup'){state.modal='join';render()} if(a==='closeModal'){state.modal=null;render()} if(a==='localDemo'){let room={code:code(),name:'單機記分',zeroCheck:true,players:['阿明','小華','阿偉'].map(n=>({id:uid(),name:n,startScore:0,score:0})),records:[],createdAt:Date.now()};saveRoom(room);state.screen='room';render()} if(a==='createRoom'){let names=$('#names').value.split(/[,，]/).map(s=>s.trim()).filter(Boolean);let start=Number($('#start').value||0);let room={code:code(),name:$('#roomName').value||'記分房',zeroCheck:$('#zero').checked,players:names.map(n=>({id:uid(),name:n,startScore:start,score:start})),records:[],createdAt:Date.now()};saveRoom(room);state.screen='room';state.modal=null;render()} if(a==='joinRoom'){let rooms=loadRooms();let c=$('#joinCode').value.trim().toUpperCase();let name=$('#joinName').value.trim();if(!rooms[c])return toast('找不到房間');r=rooms[c];if(name)r.players.push({id:uid(),name,startScore:0,score:0});saveRoom(r);state.screen='room';state.modal=null;render()} if(a==='openAdd'){state.modal='add';render()} if(a==='openPlayers'){state.modal='players';render()} if(a==='openHistory'){state.modal='history';render()} if(a==='undo'){if(!r.records.length)return toast('沒有可撤銷紀錄');r.records.pop();recalc(r);saveRoom(r);toast('已撤銷上一筆')} if(a==='submitRecord'){let items=[...document.querySelectorAll('[data-player]')].map(i=>({playerId:i.dataset.player,points:Number(i.value||0)})).filter(x=>x.points!==0);if(!items.length)return toast('請至少輸入一筆分數');r.records.push({id:uid(),createdAt:Date.now(),items,note:$('#note').value||''});recalc(r);saveRoom(r);state.modal=null;render()} if(a==='savePlayers'){r.players.forEach(p=>{let n=document.querySelector(`[data-name="${p.id}"]`);let s=document.querySelector(`[data-start="${p.id}"]`);p.name=n.value;p.startScore=Number(s.value||0)});let np=$('#newPlayer').value.trim();if(np)r.players.push({id:uid(),name:np,startScore:Number($('#newStart').value||0),score:Number($('#newStart').value||0)});recalc(r);saveRoom(r);state.modal=null;render()}}
render();
